# Generated by Django 5.2.14 on 2026-05-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='location',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=100),
        ),
    ]
