# Generated by Django 5.2.14 on 2026-05-07 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('remaining_amount', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_api.shop')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_type', models.CharField(max_length=50)),
                ('tile_name_number', models.CharField(max_length=100)),
                ('tile_type2', models.CharField(blank=True, choices=[('HL', 'HL'), ('L', 'L'), ('D', 'D'), ('F', 'F'), ('AT', 'AT')], default='AT', max_length=10)),
                ('quantity', models.IntegerField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Sale.sale')),
            ],
        ),
    ]
