# Generated by Django 5.2.14 on 2026-05-05 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tile_name_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tile_type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tile_type2',
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_type', models.CharField(max_length=50)),
                ('tile_name_number', models.CharField(max_length=100)),
                ('tile_type2', models.CharField(blank=True, choices=[('HL', 'HL'), ('L', 'L'), ('D', 'D'), ('F', 'F')], max_length=10, null=True)),
                ('quantity', models.IntegerField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Sale.sale')),
            ],
        ),
    ]
