# Generated by Django 5.2.14 on 2026-05-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0002_remove_sale_quantity_remove_sale_tile_name_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='remaining_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='tile_type2',
            field=models.CharField(blank=True, choices=[('HL', 'HL'), ('L', 'L'), ('D', 'D'), ('F', 'F'), ('AT', 'AT')], max_length=10, null=True),
        ),
    ]
