# Generated by Django 5.2.14 on 2026-05-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0003_sale_remaining_amount_alter_saleitem_tile_type2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='Sales',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='tile_type2',
            field=models.CharField(blank=True, choices=[('HL', 'HL'), ('L', 'L'), ('D', 'D'), ('F', 'F'), ('AT', 'AT')], default=5, max_length=10),
            preserve_default=False,
        ),
    ]
