# Generated by Django 5.2.14 on 2026-05-06 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0004_rename_sale_sales_alter_saleitem_tile_type2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
