# Generated by Django 5.2.14 on 2026-05-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0005_rename_sales_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='tile_type2',
            field=models.CharField(blank=True, choices=[('HL', 'HL'), ('L', 'L'), ('D', 'D'), ('F', 'F'), ('AT', 'AT')], default='AT', max_length=10),
        ),
    ]
