# Generated by Django 5.2.14 on 2026-05-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tiles',
            fields=[
                ('tile_id', models.AutoField(primary_key=True, serialize=False)),
                ('tile_name_number', models.CharField(max_length=100, unique=True)),
                ('tile_type', models.CharField(max_length=50)),
                ('price_per_box', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField()),
            ],
        ),
    ]
