# Generated by Django 5.2.14 on 2026-05-07 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('tile_id', models.AutoField(primary_key=True, serialize=False)),
                ('tile_name_number', models.CharField(max_length=100)),
                ('tile_type', models.CharField(max_length=50)),
                ('tile_type2', models.CharField(blank=True, choices=[('HL', 'HL'), ('L', 'L'), ('D', 'D'), ('F', 'F'), ('AT', 'AT')], max_length=10, null=True)),
                ('price_per_box', models.IntegerField()),
                ('stock_quantity', models.IntegerField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_api.shop')),
            ],
            options={
                'unique_together': {('tile_type', 'tile_type2', 'tile_name_number')},
            },
        ),
    ]
