# Generated by Django 5.2.14 on 2026-05-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tiles',
            new_name='Tile',
        ),
    ]
