# Generated by Django 5.2.14 on 2026-05-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiles', '0002_rename_tiles_tile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='tile_type2',
            field=models.CharField(default='AT', max_length=10),
        ),
        migrations.AlterField(
            model_name='tile',
            name='price_per_box',
            field=models.IntegerField(),
        ),
    ]
