# Generated by Django 5.2.14 on 2026-05-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiles', '0003_tile_tile_type2_alter_tile_price_per_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='tile_type2',
            field=models.CharField(blank=True, choices=[('HL', 'HL'), ('L', 'L'), ('D', 'D'), ('F', 'F'), ('AT', 'AT')], max_length=10, null=True),
        ),
    ]
