# Generated by Django 5.2.14 on 2026-05-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tiles', '0004_alter_tile_tile_type2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tile',
            unique_together={('tile_name_number', 'tile_type', 'tile_type2')},
        ),
    ]
