# Generated by Django 5.2.14 on 2026-05-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiles', '0005_alter_tile_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tile_name_number',
            field=models.CharField(max_length=100),
        ),
    ]
