# Generated by Django 5.2.14 on 2026-05-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tiles', '0006_alter_tile_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tile',
            unique_together={('tile_type', 'tile_type2', 'tile_name_number')},
        ),
    ]
